name: Dispatch Event Workflow

on:
  repository_dispatch:
    types: [build_docc]

jobs:
  dispatch_job:
    # runs-on: ubuntu-latest
    runs-on: macos-latest
    env:
      REPO: ${{ github.event.client_payload.repo }}
      TAG: ${{ github.event.client_payload.tag }}
      TOKEN: ${{ github.event.client_payload.token }}

    steps:
    - name: Run a script
      run: echo "clone $URL"
    
    - name: Download BuildDocc
      shell: bash
      run: |
        curl -sSL \
          "https://github.com/yume190/TestDoc/releases/download/0.0.1/buildDocc" \
          -o buildDocc
        chmod +x buildDocc
    
    - name: Select Xcode 15.4
      run: |
        sudo xcode-select --switch /Applications/Xcode_15.4.app

    - name: Clone Repo
      run: |
        git clone --depth 1 --branch $TAG $REPO

    - name: build swift
      run: |
        ./buildDocc \
          --repo $REPO \
          --path $(basename $REPO .git) \
          --tag $TAG \
          --token $TOKEN
