name: Dispatch Event Workflow

on:
  repository_dispatch:
    types: [build_docc]

jobs:
  dispatch_job:
    # runs-on: ubuntu-latest
    runs-on: macos-latest

    steps:
    - name: Run a script
      env:
        URL: ${{ github.event.client_payload.url }}
      run: echo "clone $URL"
